typography_spectrum: 0.13064
color:
  brandColors:
    - '#333333'
    - '#9db46c'
    - '#83965d'
    - '#454a3c'
    - '#5c6748'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Corwin Ferguson Design
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Theatre Artist
purpose: []
