name: Corwin Ferguson Design
favicon: null
layout_spectrum: 1
typography_spectrum: 0.13064
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#9db46c'
    - '#83965d'
    - '#454a3c'
    - '#5c6748'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 1
purpose: []
